### ISSUE TITLE
User CRUD and Authentication

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/SENPY#2]
# Todo

- [x] startapp api_root for urls

- [x] Startapp accounts 

- [x] Create CustomUser model and Admin

- [x] build CRUD system 

- [x] Test permisssion

- [x] setup authentication system via rest-auth all-auth
