### ISSUE TITLE
Conbine django and Vue.js

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/SENPY#5]
# Todo

- [x] Create Vue project

- [x] setting vue project to fetech api data(axios, django-cors-headers)

- [x] Create Layout(Header and Footer)

- [x] Login page

- [x] Registration page

- [x] Profile page

- [x] ProfileEdit from (description and credential)

- [x] Password Reset

- [x] Password Change

- [x] Email Change
